# Generated by Django 3.2.8 on 2021-11-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='_author',
        ),
    ]
