# Generated by Django 3.2.8 on 2021-11-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_rename_author_post__author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_author',
            field=models.ForeignKey(default='User Deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.user'),
        ),
    ]
