# Generated by Django 3.2.8 on 2021-11-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_alter_post__author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_author',
            new_name='author',
        ),
    ]
